language: node_js
node_js:
  - "4.2"

script:
  - gulp

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e3a72d897eaf2e0a226e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
